### ISSUE TITLE
Support React-Native v0.60.x ?

### ISSUE THREAD

**Issue by roziy** [netguru/sticky-parallax-header#40]

**Comment by Karniej** [comment]
Hello there, thank you for issuing this. 
There'll be a support for React-Native v.0.60 + in the near future.

**Comment by sogustavo** [comment]
@roziy, I did a workaround to work on react-native `0.61.4` until the official support come out.

- Add `"react-native-nested-scroll-view": "8.0.0"` on package.json (I don't figure, and didn't look why, but without doing this, some dependency breaks);
- Change `InternalScrollViewType` const in `node_modules\react-native-nested-scroll-view\lib\NestedScrollView.js`  from `react-native/Libraries/Components/ScrollView/InternalScrollViewType` to `react-native/Libraries/Components/ScrollView/ScrollView`;
- Create a patch with `patch-package` (just for not lose the fix in case change node_modules, and because there already is a patch in this repo that needed to be done).

I still building and testing the app, but until this moment, it's working just fine on android.

**Comment by sdjhoanborges** [comment]
same problem

**Comment by amirulasrof** [comment]
+1

**Comment by harshvitra** [comment]
Same issue

**Comment by blueromans** [comment]
+1

**Comment by jonathanmachado** [comment]
+1

**Comment by sdjhoanborges** [comment]
> @roziy, I did a workaround to work on react-native `0.61.4` until the official support come out.
> 
> * Add `"react-native-nested-scroll-view": "8.0.0"` on package.json (I don't figure, and didn't look why, but without doing this, some dependency breaks);
> * Change `InternalScrollViewType` const in `node_modules\react-native-nested-scroll-view\lib\NestedScrollView.js`  from `react-native/Libraries/Components/ScrollView/InternalScrollViewType` to `react-native/Libraries/Components/ScrollView/ScrollView`;
> * Create a patch with `patch-package` (just for not lose the fix in case change node_modules, and because there already is a patch in this repo that needed to be done).
> 
> I still building and testing the app, but until this moment, it's working just fine on android.

I didn't understand what you meant, but your fork works. If there's anyone interested please use 
`"react-native-sticky-parallax-header": "https://github.com/hgarcialeon/sticky-parallax-header.git"`

**Comment by davidwico** [comment]
Solved in https://github.com/netguru/sticky-parallax-header/pull/44
Please install version 0.0.60 and above for react-native v0.60 +
