### ISSUE TITLE
Change Tab Same Scroll Distance - Issue

### ISSUE THREAD

**Issue by stephanoparaskeva** [netguru/sticky-parallax-header#90]
When you change to next tab, the other tab is scrolled to the same amount as previous tab. This is not the desired effect because this design has little use case. There isnt a time when you scroll halfway down, and then want to be in same position on next tab. You change tab, it should go to top. Look at how instagram does this for example. On a user profile.

![ezgif com-crop](https://user-images.githubusercontent.com/40718272/81629412-faf9bf80-93fa-11ea-81c3-42f6a3169f03.gif)

In instagram, you scroll down in 1, and both scroll together untill header is collapsed. After this, scrolling in 1 will not affect the other. The other starts at top. But if you scroll in 1, and then scroll in the other, both will remember your position.

```JavaScript
    <StickyParallaxHeader
      foreground={<Foreground />}
      header={<View />}
      parallaxHeight={150}
      headerHeight={0}
      headerSize={() => {}}
      bounces={false}
      snapToEdge={false}
      tabTextStyle={showStyles.tabText}
      tabTextContainerStyle={showStyles.tabTextContainerStyle}
      tabTextContainerActiveStyle={showStyles.tabTextContainerActiveStyle}
      tabsContainerBackgroundColor='#fff'
      tabsWrapperStyle={showStyles.tabsWrapper}
      scrollEvent={() =>
        Animated.event([{ nativeEvent: { contentOffset: { y: scroll } } }], {
          useNativeDriver: true,
        })
      }
      tabs={[
        { title: 'About', content: <About user={user} /> },
        { title: 'Schedule', content: <Schedule schedules={schedules} /> },
      ]}
    />

```

**Comment by zhangSanEr** [comment]
I also encountered the same problem, when my tab1 is a webviwe because its height is too high, causing me to switch to tba2: the position changes / the content height of tba2 is too long

**Comment by waheedakhtar694** [comment]
I was also facing this problem without this lib and to fix this I wanted to switch on this lib but almost the same implementation and the problem is also in this lib and reason of this problem is `ScrollView` at the root, `ScrollView` keep getting the height of longest tab there should be some mechanism to update the `ScrollView` height at the root level component.

**Comment by pragneshpj** [comment]
@waheedakhtar694 have you found any solution about height issue?

**Comment by Patys** [comment]
Please check newest release: https://github.com/netguru/sticky-parallax-header/releases

**Comment by waheedakhtar694** [comment]
@Patys  Yeah, I have created this expo snack and that issue is fixed.

https://snack.expo.io/@waheed25/stickytabsexample

But on every tab change, it resets the tab which is fine but data re-rendering takes a jerk to display the data inside the tab, data gets hidden for a moment and then display which is a bad UX.

**Comment by pragneshpj** [comment]
@Patys Its working, Thank you

**Comment by taimourmaavan** [comment]
I am still facing the same problem with latest release
