### ISSUE TITLE
SimsScreen Android header problem

### ISSUE THREAD

**Issue by mkalayci35** [netguru/sticky-parallax-header#94]
<img width="363" alt="Screen Shot 2020-05-16 at 09 17 44" src="https://user-images.githubusercontent.com/38668796/82112524-4216e600-9756-11ea-8510-b48c0e7793b0.png">

 <Stack.Screen
        name="SimsScreen"
        component={SimsScreen}
        options={{headerShown: false}}
      />

**Comment by IdaszakDaniel** [comment]
Hi @mkalayci35 This is the example screen for the purpose of the [article about this library](https://www.netguru.com/codestories/implement-an-app-store-header-in-react-native-with-sticky-parallax-library). 

It's simplified example and solution for your issue is in the article: 
`In this example “View” with “headerWrapper” is positioned absolutely with a “top” value of 55, which is implemented for iPhones with a notch, so iPhone X and newer. For Android and older iPhone devices you should change this value by creating a helper function to compute this value.`
Take a look at other examples implementation.
